# Descarga imagen oficial de python con SO alpine
FROM python:3.8.0-alpine

# Configura directorio de trabajo
WORKDIR /usr/src/app

# Setea variables de entorno
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Instala dependencias de postgresql
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# Instala dependencias
RUN pip install --upgrade pip
COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

# Ejecuta entrypoint.prod.sh
ENTRYPOINT ["/usr/src/app/entrypoint.dev.sh"]

# Copia proyecto
COPY . .
